version: "3.3"

services:
  webapp:
    container_name: premier-league-api
    restart: always
    build: .
    ports:
      - "8080:3000"
    depends_on:
    - mongo
    mongo:
    image: mongo
    ports:
    - "27017:27017"